workflows:
  my_workflow:
    name: "Build and Test Workflow"
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/ipa
      - build/app/outputs/flutter-apk/app-release.apk
