workflows:
  my_workflow:
    name: "Build and Test Workflow"
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean iOS Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS Simulator
        script: |
          flutter build ios --simulator
      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/flutter-apk/app-release.apk
